language: node_js
node_js:
  - "8.11.3"
cache: yarn
before_script:
  - source .ethrc
script:
  - yarn test --ci --detectOpenHandles --silent --coverage --coverageReporters=text-lcov
notifications:
  email: false
  after_success: 'yarn coveralls'